#!/usr/bin/env bash
# Host golden-vector check for the PX4 LQI core.
#
# Compiles the dependency-free core with the host g++ and compares its output
# against the vectors generated by px4_trans/tools/generate_lqi_backend.py.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

g++ -std=c++17 -O2 -Wall -Wextra -Werror \
	-I"$ROOT/px4/src/modules/nn_control" \
	"$ROOT/tests/lqi_core_check.cpp" \
	-o "$WORK/lqi_core_check"

"$WORK/lqi_core_check"
